// <auto-generated />
using System;
using ConsultaExterna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsultaExterna.Migrations
{
    [DbContext(typeof(ConsultaExternaContext))]
    partial class ConsultaExternaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsultaExterna.Dominio.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<string>("Anamenesis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoCita")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamenFisico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanTratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdConsulta");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.DiagnosticoConsulta", b =>
                {
                    b.Property<int>("IdDiagnosticoConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiagnosticoConsulta"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoFarmacia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoDiagnostico")
                        .HasColumnType("integer");

                    b.HasKey("IdDiagnosticoConsulta");

                    b.HasIndex("IdConsulta");

                    b.HasIndex("IdTipoDiagnostico");

                    b.ToTable("DiagnosticoConsulta");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.NotaEvaluacion", b =>
                {
                    b.Property<int>("IdNotaEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotaEvaluacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer");

                    b.HasKey("IdNotaEvaluacion");

                    b.HasIndex("IdConsulta");

                    b.ToTable("NotaEvaluacion");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.TipoDiagnostico", b =>
                {
                    b.Property<int>("IdTipoDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDiagnostico"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTipoDiagnostico");

                    b.ToTable("TipoDiagnostico");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.DiagnosticoConsulta", b =>
                {
                    b.HasOne("ConsultaExterna.Dominio.Consulta", "Consulta")
                        .WithMany("DiagnosticoConsulta")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultaExterna.Dominio.TipoDiagnostico", "TipoDiagnostico")
                        .WithMany("DiagnosticoConsulta")
                        .HasForeignKey("IdTipoDiagnostico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("TipoDiagnostico");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.NotaEvaluacion", b =>
                {
                    b.HasOne("ConsultaExterna.Dominio.Consulta", "Consulta")
                        .WithMany("NotaEvaluacion")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.Consulta", b =>
                {
                    b.Navigation("DiagnosticoConsulta");

                    b.Navigation("NotaEvaluacion");
                });

            modelBuilder.Entity("ConsultaExterna.Dominio.TipoDiagnostico", b =>
                {
                    b.Navigation("DiagnosticoConsulta");
                });
#pragma warning restore 612, 618
        }
    }
}
